name: CI

on:
  pull_request:
    branches:
      - develop
      - main
      - qas
  push:
    branches:
      - develop
      - main
      - qas

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci
        working-directory: ./api  

      - name: Install Angular CLI
        run: npm install -g @angular/cli@13
        working-directory: ./api  

      # Executa testes unitários apenas no branch develop
      - name: Run unit tests
        if: github.ref == 'refs/heads/develop' || (github.event_name == 'pull_request' && github.base_ref == 'develop')
        run: ng test --watch=false --browsers=ChromeHeadless
        working-directory: ./api  

      # Comentar os testes de integração
      # - name: Run integration tests
      #   if: github.ref == 'refs/heads/qas' || (github.event_name == 'pull_request' && github.base_ref == 'qas') 
      #   run: ng test --watch=false --browsers=ChromeHeadless --configuration=integration  
      #   working-directory: ./api  

      # Faz login no Docker e faz o build e push da imagem Docker apenas no branch mai
      
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'  
        uses: docker/login-action@v3
        with:
          username: pixelapi  
          password: dckr_pat_141H8Srq1M-oOjg-fho4j6ezHMY 

      - name: Build and push Docker image
        if: github.ref == 'refs/heads/main'  
        uses: docker/build-push-action@v5
        with:
          context: ./api 
          file: ./api/Dockerfile  
          push: true
          tags: pixelapi/angular_app:latest  
