name: Deploy Frontend to AKS Cluster

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set AKS Context
        uses: Azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: pixelCluster
          resource-group: gr-pixel-containers

      - name: Deploy Frontend to AKS
        uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            k8s/deployment.yaml
            k8s/service.yaml
          images: |
            angularapp.azurecr.io/frontend:${{ github.sha }}
          imagepullsecrets: |
            k8s-secret-front
          namespace: ingress-basic
