name: CI

on:
  pull_request:
    branches:
      - develop
      - main
      - cron: '0 18 * * *' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci
        working-directory: ./api

      - name: Install Angular CLI
        run: npm install -g @angular/cli@13
        working-directory: ./api

      - name: Run unit tests
        if: github.ref == 'refs/heads/develop' || github.event_name == 'pull_request'
        run: ng test --watch=false --browsers=ChromeHeadless
        working-directory: ./api  

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: pixelapi
          password: dckr_pat_141H8Srq1M-oOjg-fho4j6ezHMY 

      - name: Build and push Docker image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: pixelapi/angular_app:latest

  notifyTelegramSuccess:
    runs-on: ubuntu-latest
    needs: build
    if: success() # Executa apenas se o job `build` for bem-sucedido
    steps:
      - name: Send Telegram Notification (Success)
        uses: appleboy/telegram-action@v1.0.0
        with:
          to: -4512389085
          token: 7965658930:AAH9K3d8Y2HD73FuMZ7Ys9RSjYfmfErd2zw
          message: |
            ✅ CI Pipeline Status:
            - Event: ${{ github.event_name }}
            - Branch: ${{ github.ref_name }}
            - Status: Pipeline concluído com sucesso!

  notifyTelegramFailure:
    runs-on: ubuntu-latest
    needs: build
    if: failure() # Executa apenas se o job `build` falhar
    steps:
      - name: Send Telegram Notification (Failure)
        uses: appleboy/telegram-action@v1.0.0
        with:
          to: -4512389085
          token: 7965658930:AAH9K3d8Y2HD73FuMZ7Ys9RSjYfmfErd2zw
          message: |
            ❌ CI Pipeline Failed:
            - Event: ${{ github.event_name }}
            - Branch: ${{ github.ref_name }}
            - Status: Falha no pipeline. Verifique os logs para mais detalhes!
